# Generated by Django 6.1.1 on 2026-09-20 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='sexo', max_length=1)),
                ('fecha_de_nacimiento', models.DateField(db_column='Fecha_de_Nacimiento')),
                ('celular', models.CharField(db_column='celular', max_length=8, validators=[django.core.validators.RegexValidator(message='El celular debe contener exactamente 8 dígitos.', regex='^\\d{8}$')])),
                ('cedula', models.CharField(db_column='Cedula', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener 13 dígitos numéricos seguidos de una letra mayúscula (Ej. 0010101000000A).', regex='^\\d{13}[A-Z]$')])),
                ('direccion', models.CharField(db_column='Direccion', max_length=400)),
                ('barrio', models.CharField(db_column='Barrio', max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('id_sector', models.ForeignKey(blank=True, db_column='IdSector', null=True, on_delete=django.db.models.deletion.PROTECT, to='Sector.sector')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'Pacientes',
            },
        ),
    ]
