# Generated by Django 6.1.1 on 2026-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosExamenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_resultado', models.DecimalField(blank=True, db_column='ValorResultado', decimal_places=2, max_digits=10, null=True)),
                ('interpretacion', models.CharField(blank=True, db_column='Interpretacion', max_length=500, null=True)),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True, db_column='FechaResultado')),
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Exámenes',
                'db_table': 'Resultado_Examen',
            },
        ),
    ]
