# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resultado_Examenes', '0001_initial'),
        ('Solicitud_Examenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosexamenes',
            name='id_solicitud_examen',
            field=models.ForeignKey(db_column='Id_Solicitud_Examen', on_delete=django.db.models.deletion.PROTECT, to='Solicitud_Examenes.solicituddeexamenes'),
        ),
    ]
