# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atención_cronico', '0001_initial'),
        ('Examenes_Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeExamenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicaciones', models.CharField(db_column='Indicaciones', max_length=450)),
                ('fecha_de_envio', models.DateTimeField(auto_now_add=True, db_column='fecha_de_envio')),
                ('id_atencion_cronico', models.ForeignKey(db_column='IdAtencionCronico', on_delete=django.db.models.deletion.PROTECT, to='Atención_cronico.atencioncronico')),
                ('id_examen_de_laboratorio', models.ForeignKey(db_column='IdExamen_de_Laboratorio', on_delete=django.db.models.deletion.PROTECT, to='Examenes_Laboratorio.examenesdelaboratorio')),
            ],
            options={
                'verbose_name': 'Solicitud de Examen',
                'verbose_name_plural': 'Solicitudes de Exámenes',
                'db_table': 'Solicitud_examenes',
            },
        ),
    ]
