# Generated by Django 6.1.1 on 2026-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(db_column='NombreCategoria', max_length=250, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Medicamento',
                'verbose_name_plural': 'Categorías de Medicamentos',
                'db_table': 'Categoria_Medicamento',
            },
        ),
    ]
