# Generated by Django 4.2.17 on 2026-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Gerencia', 'Gerencia')], default='Paciente', max_length=20),
        ),
    ]
