# Generated by Django 4.2.17 on 2026-10-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Gerencia', 'Gerencia'), ('Administrador', 'Administrador')], default='Paciente', max_length=20),
        ),
    ]
