# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atención_cronico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tratamiento', models.DateField(auto_now_add=True, db_column='FechaTratamiento')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=500, null=True)),
                ('id_atencion_cronico', models.ForeignKey(db_column='IdAtencionCronico', on_delete=django.db.models.deletion.PROTECT, to='Atención_cronico.atencioncronico')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'Tratamiento',
            },
        ),
    ]
