# Generated by Django 6.1.1 on 2026-09-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria_Medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(db_column='Nombre_Medicamento', max_length=250)),
                ('presentacion', models.CharField(db_column='Presentacion', max_length=150)),
                ('concentracion', models.CharField(db_column='Concentracion', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('id_categoria_medicamento', models.ForeignKey(db_column='IdCategoriaMedicamento', on_delete=django.db.models.deletion.PROTECT, to='Categoria_Medicamento.categoriamedicamento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'Medicamentos',
                'constraints': [models.UniqueConstraint(fields=('nombre_medicamento', 'concentracion'), name='UQ_Medicamento')],
            },
        ),
    ]
