# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pacientes', '__first__'),
        ('Patologias_Cronicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacientePatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_diagnostico', models.DateField(db_column='fecha_de_Diagnostico')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=500, null=True)),
                ('id_paciente', models.ForeignKey(db_column='Idpaciente', on_delete=django.db.models.deletion.PROTECT, to='Pacientes.pacientes')),
                ('id_patologia_cronica', models.ForeignKey(db_column='IDPatologiaCRonica', on_delete=django.db.models.deletion.PROTECT, to='Patologias_Cronicas.patologiascronicas')),
            ],
            options={
                'verbose_name': 'Paciente Patología',
                'verbose_name_plural': 'Pacientes Patologías',
                'db_table': 'Paciente_Patologia',
                'constraints': [models.UniqueConstraint(fields=('id_patologia_cronica', 'id_paciente'), name='UQ_Paciente_Patologia')],
            },
        ),
    ]
