# Generated by Django 6.1.1 on 2026-09-20 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='El celular debe contener exactamente 8 dígitos.', regex='^\\d{8}$')])),
                ('codigo_minsa', models.CharField(max_length=15, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_especialidad', models.ForeignKey(db_column='IdEspecialidad', on_delete=django.db.models.deletion.PROTECT, to='Especialidades.especialidades')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'Medicos',
            },
        ),
    ]
