# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicamentos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField(db_column='CantidadEntregada', validators=[django.core.validators.MinValueValidator(1, message='La cantidad entregada debe ser mayor a 0.')])),
                ('indicacion', models.CharField(db_column='Indicacion', max_length=500)),
                ('id_medicamento', models.ForeignKey(db_column='IdMedicamento', on_delete=django.db.models.deletion.PROTECT, to='Medicamentos.medicamentos')),
            ],
            options={
                'verbose_name': 'Detalle de Tratamiento',
                'verbose_name_plural': 'Detalles de Tratamientos',
                'db_table': 'Detalle_Tratamiento',
            },
        ),
    ]
