# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Detalle_Tratamiento', '0001_initial'),
        ('Tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletratamiento',
            name='id_tratamiento',
            field=models.ForeignKey(db_column='IdTratamiento', on_delete=django.db.models.deletion.PROTECT, to='Tratamiento.tratamiento'),
        ),
    ]
