# Generated by Django 6.1.1 on 2026-09-20 06:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicos', '__first__'),
        ('Paciente_Patologia', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(db_column='FechaAtencion')),
                ('peso', models.DecimalField(blank=True, db_column='Peso', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El peso debe ser mayor a 0.')])),
                ('talla', models.DecimalField(blank=True, db_column='Talla', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='La talla debe ser mayor a 0.')])),
                ('presion_arterial', models.CharField(blank=True, db_column='PresionArterial', max_length=20, null=True)),
                ('fecha_proxima_cita', models.DateField(blank=True, db_column='FechaProximaCita', null=True)),
                ('asistio', models.BooleanField(db_column='Asistio', default=True)),
                ('consulta_especializada', models.BooleanField(db_column='ConsultaEspecializada', default=False)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=1000, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('id_medico', models.ForeignKey(db_column='IdMedico', on_delete=django.db.models.deletion.PROTECT, to='Medicos.medicos')),
                ('id_paciente_patologia', models.ForeignKey(db_column='IdPaciente_Patologia', on_delete=django.db.models.deletion.PROTECT, to='Paciente_Patologia.pacientepatologia')),
            ],
            options={
                'verbose_name': 'Atención Crónico',
                'verbose_name_plural': 'Atenciones Crónicos',
                'db_table': 'Atencion_Cronico',
            },
        ),
    ]
