# Generated by Django 6.1.1 on 2026-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(db_column='NombreSector', max_length=250)),
                ('numero_sector', models.IntegerField(db_column='NumeroSector', unique=True)),
                ('zona_procedencia', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], db_column='ZonaProcedencia', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'Sector',
            },
        ),
    ]
