# Generated by Django 6.1.1 on 2026-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenesDeLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(db_column='Nombre_examen', max_length=250, unique=True)),
                ('unidad_medida', models.CharField(blank=True, db_column='UnidadMedida', max_length=50, null=True)),
                ('valor_referencia', models.CharField(blank=True, db_column='ValorReferencia', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'verbose_name': 'Examen de Laboratorio',
                'verbose_name_plural': 'Exámenes de Laboratorio',
                'db_table': 'Examenes_Laboratorio',
            },
        ),
    ]
