# Generated by Django 6.1.1 on 2026-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Codigo', max_length=20, unique=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('estado', models.PositiveSmallIntegerField(db_column='Estado', default=1)),
            ],
            options={
                'verbose_name': 'Tipo de Salida',
                'verbose_name_plural': 'Tipos de Salida',
                'db_table': 'TipoSalida',
            },
        ),
    ]
